seed: 42

srcdir: /mnt/c/Users/maria/Desktop/GITHUB/Data/icentia11k
datadir: /mnt/c/Users/maria/Desktop/GITHUB/Data/ECG_data

scaler: std

save_npz: false

splits:
  train: 0.8
  valid: 0.1
  test: 0.1

pidx: [00]

length: 512
oversampling: 1.0
avg_bpm: true
amplitude_threshold: 0.5
rhythms: [0, 1, 2, 3]  # 0: normal rhythm | 1: unknown | 2: atrial flutter | 3: atrial fibrillation
batch_size: 128