datadir: /home/pabloenrique/Data/ECG_data
model: ResNeXt.pt

resnext:
  h0_channels: 16
  cardinality: 4
  num_blocks: [3, 4, 6, 3]

loader:
  batch_size: 2
  num_workers: 0
  prefetch_factor: null

num_batches_per_epoch: 1000

optimizer:
  lr: 1.0e-5
  weight_decay: 5.0e-2

fit:
  num_epochs: 1000
  patience: 10
  min_delta: 1.0e-4
  update_every: 50

  